version: '3.8'
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: otp_db
      POSTGRES_USER: otp_user
      POSTGRES_PASSWORD: otp_pass
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
  otp-service:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: otp_user
      DB_PASSWORD: otp_pass
      DB_NAME: otp_db
    ports:
      - "8098:8098"
    env_file:
      - .env
volumes:
  db_data:
